const data = [
    {
        channelName: "WWE",
        channelLogo: "https://i.ytimg.com/vi/1yT9LC6-i64/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEmSCdldjq30QaYeVVNZGKoLwFHA",
        videoTitle: "The Undertaker's 20 greatest moments - WWE Top 10 Special Edition",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/1yT9LC6-i64/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEmSCdldjq30QaYeVVNZGKoLwFHA",
        length: "52:14",
        views: "27M views",
        uploadAt: "8 moth ago",
    },
    {
        channelName: "Fater then two",
        channelLogo: "https://yt3.ggpht.com/ytc/AAUvwnhNbi1Mah3Ck6Au-PsAbvD3QRGgYBYFSF-zaH5tJQ=s48-c-k-c0x00ffffff-no-rj",
        videoTitle: "How kar98 work?",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/igNcDEEl5to/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBY4eHWnVF-J4yHkfAK_4fKkJM8Uw",
        length: "1:37",
        views: "12K views",
        uploadAt: "1 month ago",
    },
    {
        channelName: "Darkness Developer",
        channelLogo: "https://yt3.ggpht.com/ytc/AAUvwnhwe5L0y2DxCazoLBgE0-ui6BNRWXaZlHdIG0s=s68-c-k-c0x00ffffff-no-rj",
        videoTitle: "Learn React js in one video",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/npe3Wf4tpSg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCb-nWmoE3NYX93h5i_CYq7W-Yl1g",
        length: "1:21:35",
        views: "1K views",
        uploadAt: "58 second ago",
    },
    {
        channelName: "leopoldino monteiro",
        channelLogo: "https://yt3.ggpht.com/ytc/AAUvwnjL9fVdMefV7rTZl4cE0rZXAhqEPqmxGaTWt_AHZA=s68-c-k-c0x00ffffff-no-rj",
        videoTitle: "Pantanal Matogrossense: Um Paraíso Selvagem",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/XCwRuAaKOYc/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDth45Fv5Z2_PIQi_iJaDIyaOeagA",
        length: "9:29",
        views: "24M views",
        uploadAt: "9 month ago",
    },
    {
        channelName: "Univers Kids",
        channelLogo: "https://yt3.ggpht.com/ytc/AAUvwnhNbi1Mah3Ck6Au-PsAbvD3QRGgYBYFSF-zaH5tJQ=s48-c-k-c0x00ffffff-no-rj",
        videoTitle: "Le Cobra, seigneur du désert",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/RsSIdA-B0ZY/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPJdZoSMxe1SyaNhp7W5YxLhCYeg",
        length: "14:28",
        views: "33M views",
        uploadAt: "3 month ago",
    },
    {
        channelName: "فيه وإبداع - Entertain&creativi",
        channelLogo: "https://yt3.ggpht.com/iLNj2AzJNoS1aVPgseUboXohF9aKtIG4EFifL2KTls4CAqZVSIOKpsSoqnCPxPn-kQWMvjER=s68-c-k-c0x00ffffff-no-rj",
        videoTitle: "3 SIMPLE INVENTIONS",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/VEesd81gVvU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqO5PTGaTMHRo7JyCyqYXncRFBtw",
        length: "3:10",
        views: "52M views",
        uploadAt: "6 month ago",
    },
    {
        channelName: "the wisco redneck",
        channelLogo: "https://yt3.ggpht.com/ytc/AAUvwnios6ecjLXh7tImeK8JqteEWYd-0euH6q6X5azlrQ=s68-c-k-c0x00ffffff-no-rj",
        videoTitle: "Potato cannon firing",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/PvqMWqxYuL8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUs2WiuFeW4Dm1MPVt8ytXEORFZg",
        length: "4:40",
        views: "18M views",
        uploadAt: "5 week ago",
    },
    {
        channelName: "Google Developer",
        channelLogo: "https://yt3.ggpht.com/ytc/AAUvwnhNbi1Mah3Ck6Au-PsAbvD3QRGgYBYFSF-zaH5tJQ=s48-c-k-c0x00ffffff-no-rj",
        videoTitle: "Google I/O 101: Q&A On Using Google APIs",
        videoID: "npe3Wf4tpSg",
        thumbnail: "https://i.ytimg.com/vi/7lCDEYXw3mM/default.jpg",
        length: "10:30",
        views: "3.3K views",
        uploadAt: "1 week ago"
    },
]

export default data